// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PwpuUealIv-DRKhN46qVu5w_a7KZOg8',
    appId: '1:808823490320:web:7d3908c7af9266f4b08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    authDomain: 'saapadu-groups.firebaseapp.com',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
    measurementId: 'G-85J0TDL2J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtLlxNv0H471qgnR0othHGoCHWApEFv0',
    appId: '1:808823490320:android:9175cd88a88a8020b08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACA0tVO9mNPTt45IQp9zhpZyKiLV3ycH4',
    appId: '1:808823490320:ios:b077c51d066fdd27b08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
    androidClientId: '808823490320-dr9h5ts0rs39gca5127qt8sm2blku71p.apps.googleusercontent.com',
    iosClientId: '808823490320-togbdv7c236oc0mpk17ctu9u7ouv7vgd.apps.googleusercontent.com',
    iosBundleId: 'com.saapadugroups.saapadu.saapadu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACA0tVO9mNPTt45IQp9zhpZyKiLV3ycH4',
    appId: '1:808823490320:ios:b077c51d066fdd27b08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
    androidClientId: '808823490320-dr9h5ts0rs39gca5127qt8sm2blku71p.apps.googleusercontent.com',
    iosClientId: '808823490320-togbdv7c236oc0mpk17ctu9u7ouv7vgd.apps.googleusercontent.com',
    iosBundleId: 'com.saapadugroups.saapadu.saapadu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7PwpuUealIv-DRKhN46qVu5w_a7KZOg8',
    appId: '1:808823490320:web:b1eeb4c91d2db41eb08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    authDomain: 'saapadu-groups.firebaseapp.com',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
    measurementId: 'G-0GNRY9ED14',
  );

}