// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PwpuUealIv-DRKhN46qVu5w_a7KZOg8',
    appId: '1:808823490320:web:0be60c59096e2341b08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    authDomain: 'saapadu-groups.firebaseapp.com',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
    measurementId: 'G-D7QXDXD746',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtLlxNv0H471qgnR0othHGoCHWApEFv0',
    appId: '1:808823490320:android:0bd44918706e6717b08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACA0tVO9mNPTt45IQp9zhpZyKiLV3ycH4',
    appId: '1:808823490320:ios:d981ea1abcfa9febb08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
    androidClientId: '808823490320-dr9h5ts0rs39gca5127qt8sm2blku71p.apps.googleusercontent.com',
    iosClientId: '808823490320-4m1cjkb315ugk641damg57dhji5u0dfs.apps.googleusercontent.com',
    iosBundleId: 'com.saapadugroups.saapadu.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACA0tVO9mNPTt45IQp9zhpZyKiLV3ycH4',
    appId: '1:808823490320:ios:d981ea1abcfa9febb08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
    androidClientId: '808823490320-dr9h5ts0rs39gca5127qt8sm2blku71p.apps.googleusercontent.com',
    iosClientId: '808823490320-4m1cjkb315ugk641damg57dhji5u0dfs.apps.googleusercontent.com',
    iosBundleId: 'com.saapadugroups.saapadu.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7PwpuUealIv-DRKhN46qVu5w_a7KZOg8',
    appId: '1:808823490320:web:0be60c59096e2341b08795',
    messagingSenderId: '808823490320',
    projectId: 'saapadu-groups',
    authDomain: 'saapadu-groups.firebaseapp.com',
    databaseURL: 'https://saapadu-groups-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saapadu-groups.firebasestorage.app',
    measurementId: 'G-D7QXDXD746',
  );

}